<?php
/**
 * @file
 * Code for the Material feature.
 */

include_once('material.features.inc');

/**
 * Defines a new feeds parser to parse librarydata calendar feeds.
 *
 * @return array $info
 */
function material_feeds_plugins() {
  $info = array();
  $info['LibrarydataParser'] = array(
    'name' => "Librarydata parser",
    'description' => t('Parse librarydata feed'),
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'LibrarydataParser',
      'file' => 'librarydata.class.inc',
      'path' => drupal_get_path('module', 'material' ) . '/includes',
    ),
  );
  return $info;
}

/**
 * Make sure that the feed parser cache is cleared on module activation.
 */
function material_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}